In [68]:
from column import TNN_Col
from layer import Layer
from submodule import *
from backend.backend import * 
import argparse
import os
from rich.console import Console
from tnn_mdls.func_mdls import *
from tnn_mdls.tb_func_mdls import *
import time
from veriloggen import *
import copy
from model import Model
import numpy as np

In [190]:
rfsize = 1
nprev = 1
inputsize = 9
stride = 1
num_k = int((((inputsize-rfsize)/stride)+1) * (((inputsize-rfsize)/stride)+1))
in_width = inputsize*inputsize*nprev
p = rfsize*rfsize*nprev
out_width = p*num_k

In [191]:
layer_in = np.arange(in_width)
layer_out = np.zeros(out_width)

In [192]:
layer_in

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [193]:
num_k

81

In [194]:
n_col = int(((inputsize-rfsize)/stride)+1)
n_row = int(((inputsize-rfsize)/stride)+1)
col = inputsize
row = inputsize

for k in range(num_k):
    ky = int(np.floor(k/n_col))
    kx = int(np.floor(k%n_row))
    
    for r in range(rfsize):
        out1 = rfsize*rfsize*nprev*k+r*rfsize*nprev
        out2 = out1+(rfsize*nprev-1)
        in1 = ((kx + ky*inputsize)*stride + inputsize*r)*nprev
        in2 = in1+(rfsize*nprev-1)
        #print(((kx + ky*inputsize)*stride + inputsize*r))
        #print(kx*stride)
        #print(in1, in2)
        layer_out[out1:out2+1] = layer_in[in1:in2+1]

In [195]:
layer_out

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80.])

In [196]:
m = np.zeros((inputsize,inputsize))
count = 0
for i in range(inputsize):
    for j in range(inputsize):
        m[i][j] = count
        count += 1

In [197]:
m

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23., 24., 25., 26.],
       [27., 28., 29., 30., 31., 32., 33., 34., 35.],
       [36., 37., 38., 39., 40., 41., 42., 43., 44.],
       [45., 46., 47., 48., 49., 50., 51., 52., 53.],
       [54., 55., 56., 57., 58., 59., 60., 61., 62.],
       [63., 64., 65., 66., 67., 68., 69., 70., 71.],
       [72., 73., 74., 75., 76., 77., 78., 79., 80.]])

In [63]:
layer_out

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [30]:
out_width, num_k

(30000, 625)

In [31]:
in_width

8112